version: '3.8'
services:
  sql-db:
    env_file:
      - .env
    image: postgres:latest
    container_name: RecetasDB
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      - data-recetas:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${PORT_POSTGRES_HOST}:${PORT_POSTGRES_DOCKER}"
    networks:
      - net-recetas
#  java-app:
#    container_name: RecetasBackend
#    image: java-app:0.0.1
#    build:
#      context: ./RecetasApp
#      dockerfile: java.Dockerfile
#    restart: always
#    ports:
#      - "${PORT_BACKEND_HOST}:${PORT_BACKEND_DOCKER}"
#    networks:
#      - net-recetas
#    depends_on:
#      - sql-db
networks:
  net-recetas:
    driver: bridge
volumes:
  data-recetas: