INSERT INTO region (name) VALUES ('Arica y Parinacota'),
                                 ('Tarapacá'),
                                 ('Antofagasta'),
                                 ('Atacama'),
                                 ('Coquimbo'),
                                 ('Valparaíso'),
                                 ('O''Higgins'),
                                 ('Maule'),
                                 ('Ñuble'),
                                 ('Bio-Bio'),
                                 ('Araucanía'),
                                 ('Los Rios'),
                                 ('Los Lagos'),
                                 ('Aysén'),
                                 ('Magallanes y Antártica Chile'),
                                 ('Metropolitana de Santiago');

insert into comunas (name,id_region) VALUES  ('Arica',1),
                                            ('Camarones',1),
                                            ('General Lagos',1),
                                            ('Putre',1),
                                            ('Alto Hospicio',2),
                                            ('Camiña',2),
                                            ('Colchane',2),
                                            ('Huara',2),
                                            ('Iquique',2),
                                            ('Pica',2),
                                            ('Pozo Almonte',2),
                                            ('Antofagasta',3),
                                            ('Calama',3),
                                            ('María Elena',3),
                                            ('Mejillones',3),
                                            ('Ollagüe',3),
                                            ('San Pedro de Atacama',3),
                                            ('Sierra Gorda',3),
                                            ('Taltal',3),
                                            ('Tocopilla',3),
                                            ('Alto del Carmen',4),
                                            ('Caldera',4),
                                            ('Chañaral',4),
                                            ('Copiapó',4),
                                            ('Diego de Almagro',4),
                                            ('Freirina',4),
                                            ('Huasco',4),
                                            ('Tierra Amarilla',4),
                                            ('Vallenar',4),
                                            ('Andacollo',5),
                                            ('Canela',5),
                                            ('Combarbalá',5),
                                            ('Coquimbo',5),
                                            ('Illapel',5),
                                            ('La Higuera',5),
                                            ('La Serena',5),
                                            ('Los Vilos',5),
                                            ('Monte Patria',5),
                                            ('Ovalle',5),
                                            ('Paihuano',5),
                                            ('Punitaqui',5),
                                            ('Río Hurtado',5),
                                            ('Salamanca',5),
                                            ('Vicuña',5),
                                            ('Algarrobo',6),
                                            ('Cabildo',6),
                                            ('Calera',6),
                                            ('Calle Larga',6),
                                            ('Cartagena',6),
                                            ('Casablanca',6),
                                            ('Catemu',6),
                                            ('Concón',6),
                                            ('El Quisco',6),
                                            ('El Tabo',6),
                                            ('Hijuelas',6),
                                            ('Isla de Pascua',6),
                                            ('Juan Fernández',6),
                                            ('La Cruz',6),
                                            ('La Ligua',6),
                                            ('Limache',6),
                                            ('Llaillay',6),
                                            ('Los Andes',6),
                                            ('Nogales',6),
                                            ('Olmué',6),
                                            ('Panquehue',6),
                                            ('Papudo',6),
                                            ('Petorca',6),
                                            ('Puchuncaví',6),
                                            ('Putaendo',6),
                                            ('Quillota',6),
                                            ('Quilpué',6),
                                            ('Quintero',6),
                                            ('Rinconada',6),
                                            ('San Antonio',6),
                                            ('San Esteban',6),
                                            ('San Felipe',6),
                                            ('Santa María',6),
                                            ('Santo Domingo',6),
                                            ('Valparaíso',6),
                                            ('Villa Alemana',6),
                                            ('Viña del Mar',6),
                                            ('Zapallar',6),
                                            ('Chépica',7),
                                            ('Chimbarongo',7),
                                            ('Codegua',7),
                                            ('Coínco',7),
                                            ('Coltauco',7),
                                            ('Doñihue',7),
                                            ('Graneros',7),
                                            ('La Estrella',7),
                                            ('Las Cabras',7),
                                            ('Lituenche',7),
                                            ('Lolol',7),
                                            ('Machalí',7),
                                            ('Malloa',7),
                                            ('Marchihue',7),
                                            ('Mostazal',7),
                                            ('Nancagua',7),
                                            ('Navidad',7),
                                            ('Olivar',7),
                                            ('Palmilla',7),
                                            ('Paredones',7),
                                            ('Peumo',7),
                                            ('Pichidegua',7),
                                            ('Pichilemu',7),
                                            ('Placilla',7),
                                            ('Pumanque',7),
                                            ('Quinta de Tilcoco',7),
                                            ('Rancagua',7),
                                            ('Rengo',7),
                                            ('Requínoa',7),
                                            ('San Fernando',7),
                                            ('Santa Cruz',7),
                                            ('San Vicente',7),
                                            ('Cauquenes',8),
                                            ('Chanco',8),
                                            ('Colbún',8),
                                            ('Constitución',8),
                                            ('Curepto',8),
                                            ('Curicó',8),
                                            ('Empedrado',8),
                                            ('Hualañé',8),
                                            ('Licantén',8),
                                            ('Linares',8),
                                            ('Longaví',8),
                                            ('Maule',8),
                                            ('Molina',8),
                                            ('Parral',8),
                                            ('Pelarco',8),
                                            ('Pelluhue',8),
                                            ('Pencahue',8),
                                            ('Rauco',8),
                                            ('Retiro',8),
                                            ('Río Claro',8),
                                            ('Romeral',8),
                                            ('Sagrada Familia',8),
                                            ('San Clemente',8),
                                            ('San Javier',8),
                                            ('San Rafael',8),
                                            ('Talca',8),
                                            ('Teno',8),
                                            ('Vichuquén',8),
                                            ('Villa Alegre',8),
                                            ('Yerbas Buenas',8),
                                            ('Bulnes',9),
                                            ('Chillán',9),
                                            ('Chillán Viejo',9),
                                            ('Cobquecura',9),
                                            ('Coelemu',9),
                                            ('Coihueco',9),
                                            ('El Carmen',9),
                                            ('Ninhue',9),
                                            ('Ñinhue',9),
                                            ('Pemuco',9),
                                            ('Pinco',9),
                                            ('Portezuelo',9),
                                            ('Quillón',9),
                                            ('Quirihue',9),
                                            ('Ránquil',9),
                                            ('San Carlos',9),
                                            ('San Fabián',9),
                                            ('San Ignacio',9),
                                            ('San Nicolás',9),
                                            ('Treguaco',9),
                                            ('Yungay',9),
                                            ('Alto Biobío',10),
                                            ('Antuco',10),
                                            ('Arauco',10),
                                            ('Cabrero',10),
                                            ('Cañete',10),
                                            ('Chiguayante',10),
                                            ('Concepción',10),
                                            ('Contulmo',10),
                                            ('Coronel',10),
                                            ('Curanilahue',10),
                                            ('Florida',10),
                                            ('Hualpén',10),
                                            ('Hualqui',10),
                                            ('Laja',10),
                                            ('Lebu',10),
                                            ('Los Alamos',10),
                                            ('Los Angeles',10),
                                            ('Lota',10),
                                            ('Mulchén',10),
                                            ('Nacimiento',10),
                                            ('Negrete',10),
                                            ('Penco',10),
                                            ('Quilaco',10),
                                            ('Quilleco',10),
                                            ('San Pedro de la Paz',10),
                                            ('San Rosendo',10),
                                            ('Santa Bárbara',10),
                                            ('Santa Juana',10),
                                            ('Talcahuano',10),
                                            ('Tirúa',10),
                                            ('Tomé',10),
                                            ('Tucapel',10),
                                            ('Yumbel',10),
                                            ('Angol',11),
                                            ('Carahue',11),
                                            ('Cholchol',11),
                                            ('Collipulli',11),
                                            ('Cunco',11),
                                            ('Caracautín',11),
                                            ('Curarrehue',11),
                                            ('Ercilla',11),
                                            ('Freire',11),
                                            ('Galvarino',11),
                                            ('Gorbea',11),
                                            ('Lautaro',11),
                                            ('Loncoche',11),
                                            ('Lonquimay',11),
                                            ('Los Sauces',11),
                                            ('Lumaco',11),
                                            ('Melipeuco',11),
                                            ('Nueva Imperial',11),
                                            ('Padre Las Casas',11),
                                            ('Perquenco',11),
                                            ('Pitrufquén',11),
                                            ('Pucón',11),
                                            ('Purén',11),
                                            ('Renaico',11),
                                            ('Saavedra',11),
                                            ('Temuco',11),
                                            ('Teodoro Schmidt',11),
                                            ('Toltén',11),
                                            ('Traiguén',11),
                                            ('Victoria',11),
                                            ('Vilcún',11),
                                            ('Villarica',11),
                                            ('Corral',12),
                                            ('Futrono',12),
                                            ('Lago Ranco',12),
                                            ('Máfil',12),
                                            ('Mariquina',12),
                                            ('Paillaco',12),
                                            ('Panguipulli',12),
                                            ('Río Bueno',12),
                                            ('Ancud',12),
                                            ('Calbuco',13),
                                            ('Castro',13),
                                            ('Chaitén',13),
                                            ('Chonchi',13),
                                            ('Cochamó',13),
                                            ('Curazo de Vélez',13),
                                            ('Dalcahue',13),
                                            ('Fresia',13),
                                            ('Frutillar',13),
                                            ('Futaleufú',13),
                                            ('Hualaihué',13),
                                            ('Llanquihue',13),
                                            ('Los Muermos',13),
                                            ('Maullín',13),
                                            ('Osorno',13),
                                            ('Palena',13),
                                            ('Puerto Montt',13),
                                            ('Puerto Octay',13),
                                            ('Puerto Varas',13),
                                            ('Puqueldón',13),
                                            ('Purranque',13),
                                            ('Puyehue',13),
                                            ('Queilén',13),
                                            ('Quellón',13),
                                            ('Quemchi',13),
                                            ('Quinchao',13),
                                            ('Río Negro',13),
                                            ('San Juan de la Costa',13),
                                            ('San Pablo',13),
                                            ('Aysén',14),
                                            ('Chile Chico',14),
                                            ('Cisnes',14),
                                            ('Cochrame',14),
                                            ('Coyhaique',14),
                                            ('Guaitecas',14),
                                            ('Lago Verde',14),
                                            ('O''Higgins',14),
                                            ('Río Ibañez',14),
                                            ('Tortel',14),
                                            ('Antártica',15),
                                            ('Cabo de Hornos',15),
                                            ('Laguna Blanca',15),
                                            ('Natales',15),
                                            ('Porvenir',15),
                                            ('Primavera',15),
                                            ('Punta Arenas',15),
                                            ('Río Verde',15),
                                            ('San Gregorio',15),
                                            ('Timaukel',15),
                                            ('Torres del Paine',15),
                                            ('Alhué',16),
                                            ('Buin',16),
                                            ('Calera de Tango',16),
                                            ('Cerrillos',16),
                                            ('Cerro Navia',16),
                                            ('Colina',16),
                                            ('Conchalí',16),
                                            ('Curacaví',16),
                                            ('El Bosque',16),
                                            ('El Monte',16),
                                            ('Estación Central',16),
                                            ('Huechuraba',16),
                                            ('Independencia',16),
                                            ('Isla de Maipo',16),
                                            ('La Cisterna',16),
                                            ('La Florida',16),
                                            ('La Granja',16),
                                            ('Lampa',16),
                                            ('La Pintana',16),
                                            ('La Reina',16),
                                            ('Las Condes',16),
                                            ('Lo Barnechea',16),
                                            ('Lo Espejo',16),
                                            ('Lo Prado',16),
                                            ('Macul',16),
                                            ('Maipú',16),
                                            ('María Pinto',16),
                                            ('Melipilla',16),
                                            ('Ñuñoa',16),
                                            ('Padre Hurtado',16),
                                            ('Paine',16),
                                            ('Pedro Aguirre Cerda',16),
                                            ('Peñarol',16),
                                            ('Peñalolén',16),
                                            ('Pirque',16),
                                            ('Providencia',16),
                                            ('Pudahuel',16),
                                            ('Puente Alto',16),
                                            ('Quilicura',16),
                                            ('Quinta Normal',16),
                                            ('Recoleta',16),
                                            ('Renca',16),
                                            ('San Bernardo',16),
                                            ('San Joaquín',16),
                                            ('San José de Maipo',16),
                                            ('San Miguel',16),
                                            ('San Pedro',16),
                                            ('San Ramón',16),
                                            ('Santiago',16),
                                            ('Talagante',16),
                                            ('TilTil',16),
                                            ('Vitacura',16);


insert into provision (name) VALUES('Fonasa'),
                                    ('Isapre'),
                                    ('Particular');

insert into doctor_specialities (name) VALUES ('Dermatólogo'),
                                              ('Medicina General');


insert into users(username,role,enabled,password,change_new_pass,created)values ('76.302.859-3','ADMIN',true,'$2a$10$dB6OzNd9KC2MPY6/NiuUfudbfTIKjtgx0nB4U/dxdVZLXFDGLN1MW',true,'2023-10-26'),
                                                                                ('22.914.244-5','DOCTOR',true,'$2a$10$8ZpzgDtUMinI8fsZ0PIUPePUfbSE8fwsbeerwjI3BKdlvHJlM/mgu',true,'2023-10-21'),
                                                                                ('11.111.111-1','DOCTOR',true,'$2a$10$w383COf/LVDBYkXUO2tf.e8/exbf5/j1f4XMiHr7gXX6mi5UxcAnW',true,'2023-10-21'),
                                                                                ('20.150.262-4','PATIENT',true,'$2a$10$MJFoh42K7lQaQ/x1qp7Bd.4NWbL40x8bWtjz2MzO6MzcuMZw7gdeW',true,'2023-10-21'),
                                                                                ('19.611.371-1','PATIENT',true,'$2a$10$BzE2zjWLY1ZLdQt/LBCEbuPlCPzWXTBUAusSe4ewhFGPfvH8zbX2K',true,'2023-10-21');

                                                                                
insert into employees(rut,name,lastname,id_user) VALUES ('76.302.859-3','BIOFARMA','S.A.',1);

insert into method_pay(name) values('EFECTIVO'),
                                   ('DEBITO'),
                                   ('CRÉDITO'),
                                   ('TRANSFERENCIA');

insert into doctors (rut,id_speciality,name,lastname,date_born,id_comuna,address,phone,email,id_user) VALUES ('22.914.244-5',2, 'JOSÉ HERMINIO', 'MOROCHO GORDILLO', '1979-08-01',1, 'Av. Las Rastras #1285 piso 8 - Ed.Centro Pichimapu  ','+569 52116195','mail@mail.cl',2),
                                                                                                      ('11.111.111-1',1, 'Doctor', 'Test', '1997-10-21',1, 'Direccion Test','+569 52116195','mail@mail.cl',3),
                                                                                                      ('76.302.859-3',2, 'BIOFARMA','S.A.','2023-10-21',120,'Prat #116','752327463','contacto@biofarma.cl',1);

insert into patients (rut,name,lastname,date_born,id_comuna,address,phone,email,id_provision,id_user) VALUES ('19.611.371-1', 'MATÍAS NICOLÁS', 'VALDÉS REYES', '1997-10-21', 1, 'Villa Dona Patricia psj. Lontue #221','+569 52116195','matias.valdesr3@gmail.com',1,4),
                                                                                               ('20.150.262-4', 'RENATA', 'QUIJADA CATRILEO', '1996-10-26', 120, 'Villa Dona Patricia','+569 9999999','renata.quijada@gmail.com',1,3);



insert into unidad_medicion (name) VALUES   ('Kg'),
                                            ('g'),
                                            ('mg'),
                                            ('mcg'),
                                            ('Lt'),
                                            ('ml'),
                                            ('cc'),
                                            ('UI'),
                                            ('un'),
                                            ('%');

insert into materia_prima (name,id_unidadmedicion) VALUES ('ARBUTINA',10),
                                                          ('AZUFRE PRECIPITADO',10),
                                                          ('BENZOCAÍNA',10),
                                                          ('BETAMETASONA',10),
                                                          ('BIFONAZOL',10),
                                                          ('CAOLIN MEDICINAL',10),
                                                          ('CELLOSIZE',10),
                                                          ('CERAMIDAS',10),
                                                          ('CLINDAMICINA',10),
                                                          ('CLOBETASOL PROPIONATO',10),
                                                          ('CLOTRIMAZOL',10),
                                                          ('COENZIMA Q-10',10),
                                                          ('COLÁGENO HIDROLIZADO',3),
                                                          ('DEXAMETASONA',10),
                                                          ('D-PHANTENOL',10),
                                                          ('ELASTINA HIDROLIZADA',10),
                                                          ('ERITROMICINA BASE',10),
                                                          ('ESENCIA DE LIMÓN',10),
                                                          ('ETHANOL ABSOLUTO',10),
                                                          ('EXT. ALOE VERA',10),
                                                          ('EXT. ÁRNICA',10),
                                                          ('EXT. CALÉNDULA',10),
                                                          ('EXT. CASTAÑO DE INDIAS',10),
                                                          ('EXT. CENTELLA ASIÁTICA',10),
                                                          ('EXT. COLA CABALLO',10),
                                                          ('EXT. DE MALVA',10),
                                                          ('EXT. DE MATICO',10),
                                                          ('EXT. DE MELISSA',10),
                                                          ('EXT. GERMEN DE TRIGO',10),
                                                          ('EXT. GINKGO BILOBA T.M.',10),
                                                          ('EXT. HAMAMELIS',10),
                                                          ('EXT. HEDERA HELIX',10),
                                                          ('EXT. MANZANILLA',10),
                                                          ('EXT. MURTILLA',10),
                                                          ('FORMALINA 37%',10),
                                                          ('GENTAMICINA',10),
                                                          ('GLICERINA',10),
                                                          ('HIDROCORTISONA',10),
                                                          ('HIDROQUINONA',10),
                                                          ('IODOGENE',10),
                                                          ('KETOCONAZOL',10),
                                                          ('LAURIL SULFATO DE SODIO',10),
                                                          ('LIDOCAÍNA',10),
                                                          ('LIPOWAX D',10),
                                                          ('MENTOL CRISTAL',10),
                                                          ('METILPARABENO',10),
                                                          ('METRONIDAZOL',10),
                                                          ('MICONAZOL',10),
                                                          ('MINOXIDIL',10),
                                                          ('NEOMICINA SULFATO',10),
                                                          ('NIFEDIPINA',10),
                                                          ('NISTATINA',10),
                                                          ('ÓXIDO DE ZINC',10),
                                                          ('PERMETRINA',10),
                                                          ('PERÓXIDO DE BENZOÍLO',10),
                                                          ('PODOFILINA',10),
                                                          ('PODOFILOTOXINA',10),
                                                          ('POTASIO YODURO',10),
                                                          ('PRILOCAÍNA',10),
                                                          ('PROCAÍNA',10),
                                                          ('PROPILENGLICOL',10),
                                                          ('PROPILPARABENO',10),
                                                          ('RESORCINOL',10),
                                                          ('SALICILATO DE METILO',10),
                                                          ('SORBITOL 70%',10),
                                                          ('SULFATO DE COBRE',10),
                                                          ('SULFATO DE SODIO',10),
                                                          ('SYN AKE',10),
                                                          ('SYN COLL',10),
                                                          ('TACROLIMUS',10),
                                                          ('TERBINAFINA',10),
                                                          ('TETRACAÍNA',10),
                                                          ('TIMOLOL',10),
                                                          ('TINTURA BENJUI',10),
                                                          ('TREMENTINA/AGUARRÁS',10),
                                                          ('TRIAMCINOLONA',10),
                                                          ('TRICHOGEN',10),
                                                          ('TRIETANOLAMINA',10),
                                                          ('TWEEN 80/POLISORBATO',10),
                                                          ('UREA',10),
                                                          ('VITAMINA A',10),
                                                          ('VITAMINA D',10),
                                                          ('VITAMINA E',10),
                                                          ('YODO RESUBLIMADO',10),
                                                          ('ZINC ACETATO',10),
                                                          ('ÁCIDO ACETILSALICÍLICO',3),
                                                          ('ÁCIDO CÍTRICO',3),
                                                          ('ÁCIDO FÓLICO',3),
                                                          ('ÁCIDO LINOLEICO CONJUGADO',3),
                                                          ('ÁCIDO URSODESOXICÓLICO',3),
                                                          ('ACETILCISTEÍNA',3),
                                                          ('ALGAS MARINAS',3),
                                                          ('ALMIDÓN DE MAIZ/TRIGO',3),
                                                          ('ALOE VERA',3),
                                                          ('AMITRIPTILINA',3),
                                                          ('AMLODIPINO',3),
                                                          ('ARÁNDANO ROJO',3),
                                                          ('ARTICHOKE',3),
                                                          ('ATENOLOL',3),
                                                          ('ATORVASTATINA',3),
                                                          ('BICARBONATO DE SODIO',3),
                                                          ('BIOTINA',3),
                                                          ('BUPROPION',3),
                                                          ('BUSPIRONA',3),
                                                          ('CAFÉ VERDE',3),
                                                          ('CAFEÍNA',3),
                                                          ('CAIGUA',3),
                                                          ('CALCIO CARBONATO',3),
                                                          ('CAPTOPRIL',3),
                                                          ('CARDO MARIANO/SILIMARINA',3),
                                                          ('CÁSCARA SAGRADA',3),
                                                          ('CASTAÑO DE INDIAS',3),
                                                          ('CENTELLA/HYDROCOTYLE',3),
                                                          ('CITRATO DE POTASIO',3),
                                                          ('CITRATO DE SODIO',3),
                                                          ('CITRUS DECUMANUS/NARANJA AMARGA',3),
                                                          ('CLORDIAZEPÓXIDO',3),
                                                          ('COLECALCIFEROL',3),
                                                          ('CONDROITÍN SULFATO',3),
                                                          ('CRATAEGUS',3),
                                                          ('DHA',3),
                                                          ('DOMPERIDONA',3),
                                                          ('ENALAPRIL',3),
                                                          ('ESPIRONOLACTONA',3),
                                                          ('FAMOTIDINA',3),
                                                          ('FASEOLAMINA/PHASEOLUS VULGARIS',3),
                                                          ('FENILPROPANOLAMINA',3),
                                                          ('FENOLFTALEÍNA',3),
                                                          ('FENTERMINA',3),
                                                          ('FIBRA VEGETAL',3),
                                                          ('FINASTERIDE',3),
                                                          ('FLUOXETINA',3),
                                                          ('FUCUS VESICULOSUS',3),
                                                          ('FUROSEMIDA',3),
                                                          ('GERMEN DE TRIGO',3),
                                                          ('GINKO BILBOA',3),
                                                          ('GINSENG',3),
                                                          ('GLUCOSAMINA SULFATO',3),
                                                          ('GOJI',3),
                                                          ('GRAVIOLA',3),
                                                          ('GUARANÁ/GUARANINA',3),
                                                          ('HERCAMPURI',3),
                                                          ('HIDROCLOROTIAZIDA',3),
                                                          ('HYPERICUM',3),
                                                          ('INULINA',3),
                                                          ('ISOFLAVONA DE SOYA',3),
                                                          ('L-ARGININA',3),
                                                          ('L-CARNITINA',3),
                                                          ('L-CISTEÍNA',3),
                                                          ('LECITINA DE SOYA',3),
                                                          ('L-GLUTAMINA',3),
                                                          ('LIOTIRONINA SÓDICA',3),
                                                          ('L-METIONINA',3),
                                                          ('L-TAURINA',3),
                                                          ('L-TEANINA',3),
                                                          ('L-TIROSINA',3),
                                                          ('L-TRIPTÓFANO',3),
                                                          ('MACA',3),
                                                          ('MAGNESIA CALCINADA',3),
                                                          ('MAGNESIO SULFATO',3),
                                                          ('MAGNESIO CARBONATO',3),
                                                          ('MALTODEXTRINA',3),
                                                          ('MAQUI EXTRACTO',3),
                                                          ('MELATONINA',3),
                                                          ('MELISSA',3),
                                                          ('MELOXICAM',3),
                                                          ('METFORMINA',3),
                                                          ('METOCLOPRAMIDA',3),
                                                          ('MORINGA',3),
                                                          ('NONI',3),
                                                          ('OKRA',3),
                                                          ('OMEPRAZOL',3),
                                                          ('ORLISTAT',3),
                                                          ('ÓXIDO DE MAGNESIO',3),
                                                          ('PARACETAMOL',3),
                                                          ('PASIFLORA',3),
                                                          ('PEPA DE CALABAZA',3),
                                                          ('PICOLINATO DE CROMO',4),
                                                          ('PICOSULFATO DE SÓDICO',3),
                                                          ('POLIETILENGLICOL 3350',3),
                                                          ('POMELO',3),
                                                          ('POTASIO BROMURO',3),
                                                          ('POTASIO CLORURO',3),
                                                          ('PROPRANOLOL',3),
                                                          ('SAN JUAN',3),
                                                          ('SAW PALMETTO',3),
                                                          ('SEN',3),
                                                          ('SERTRALINA',3),
                                                          ('SILDENAFIL',3),
                                                          ('SIMETICONA C',3),
                                                          ('SPRIRULINA',3),
                                                          ('TÉ DE MATCHA',3),
                                                          ('TOPIRAMATO',3),
                                                          ('TRAMADOL',3),
                                                          ('TRIMEBUTINO',3),
                                                          ('UVA URSI',3),
                                                          ('VALERIANA',3),
                                                          ('VINAGRE DE SIDRA/MANZANA',3),
                                                          ('VITAMINA B1/TIAMINA',3),
                                                          ('VITAMINA B2/RIVOFLAVINA',3),
                                                          ('VITAMINA B6',3),
                                                          ('VITAMINA D3',8),
                                                          ('VITIS VINIFERA',3),
                                                          ('ZINC SULFATO',3);


insert into formato_farmaceutico (name,id_unidadmedicion) VALUES ('CAPSULAS',9),
                                                                 ('CREMA',2),
                                                                 ('GEL',2),
                                                                 ('JARABE',7),
                                                                 ('LOCIÓN',6),
                                                                 ('SHAMPOO',6),
                                                                 ('TALCO',2),
                                                                 ('ESMALTE',6),
                                                                 ('SOLUCIÓN',6),
                                                                 ('UNGÜENTO',2),
                                                                 ('SACHET',9),                                                                
                                                                 ('FRACCIONAMIENTO',2);


insert into format_details (name,id_format) VALUES ('LACTOSA',1),
                                                     ('TALCO',1),
                                                     ('BASE',2),
                                                     ('BASE FLUIDA',2),
                                                     ('BASE HUMECTANTE',2),
                                                     ('BASE OIL FREE',2),
                                                     ('BASE COLD CREAM',2),
                                                     ('BASE NO COMEDOGÉNICA',2),
                                                     ('NOVOBASE II',2),
                                                     ('NO IÓNICA',2),
                                                     ('BASE',3),
                                                     ('CARBOPOL',3),
                                                     ('CRIOGEL',3),
                                                     ('TERMOGEL',3),
                                                     ('BASE SIN AZÚCAR',4),
                                                     ('BASE AZUCARADA',4),
                                                     ('BASE',5),
                                                     ('CORPORAL',5),
                                                     ('BASE',6),
                                                     ('BASE',7),
                                                     ('BASE',8),
                                                     ('BASE',9),
                                                     ('COLODION ELÁSTICO',9),
                                                     ('PLASTIBASE',10),
                                                     ('NORMAL',11),
                                                     ('NORMAL',12);